id = "confluence-context-server"
name = "Confluence Context Server"
version = "1.0.0"
schema_version = 1
authors = ["Mouhamad Al Mounayar muhammad.mnayar@gmail.com"]
description = "Confluence Context Server"
repository = "https://github.com/mouhamadalmounayar/confluence-context-server"

[context_servers.confluence-context-server]
name = "Confluence Context Server"
